#from . import production_lines
#from . import res_config_settings
#from . import sale_order
#from . import purchase
#from . import account
#from . import product
#from . import mrp_bom
#from . import mrp_production
#from . import stock_picking
#from . import mrp_mps
#from . import mrp_unbuild
from . import pharmaceutical_product
#from . import stock_move
#from . import stock_quant
#from . import mrp_production_simulation_lot
#from . import stock_move_line
#from . import scss_editor
#from . import quality
